import logging
import json
from anki_connect import invoke as anki_invoke
from pathlib import Path
from tqdm import tqdm

from models.models import ModelListen, ModelRead, ModelWrite

logger = logging.getLogger(__name__)

merged1 = [
    ("Academia", "Academia"),
    ("Academic", "Academia"),
    ("Accounting", "Business"),
    ("Acoustics", "Science"),
    ("Activity", "Activity"),
    ("Adventure", "Recreation"),
    ("Advertising", "Marketing"),
    ("Advocacy", "Social_Justice"),
    ("Aerospace", "Engineering"),
    ("Aid", "Non-profit"),
    ("Alternative", "General"),
    ("AmE", "English"),
    ("American", "Culture"),
    ("American_Football", "Sports"),
    ("Analysis", "Problem-Solving"),
    ("Anatomy", "Biology"),
    ("Animal", "Animal"),
    ("Animal_Behavior", "Animal"),
    ("Animal_Husbandry", "Farming"),
    ("Animal_Science", "Biology"),
    ("Animal_Sounds", "Animal"),
    ("Animal_Training", "Animal"),
    ("Animal_welfare", "Animal"),
    ("Animals", "Animal"),
    ("Anthropology", "Social_Science"),
    ("Appearance", "Fashion"),
    ("Archaeology", "History"),
    ("Architecture", "Art"),
    ("Argument", "Communication"),
    ("Argumentation", "Communication"),
    ("Art", "Art"),
    ("Art_Criticism", "Art"),
    ("Artificial_Intelligence", "Computer_Science"),
    ("Arts", "Art"),
    ("Astrology", "Science"),
    ("Astronomy", "Science"),
    ("Athletics", "Sports"),
    ("Auction", "Business"),
    ("Audio", "Technology"),
    ("Automotive", "Engineering"),
    ("Aviation", "Transportation"),
    ("Awards", "Recognition"),
    ("Baseball", "Sports"),
    ("Basketball", "Sports"),
    ("Beauty", "Fashion"),
    ("Behavior", "Psychology"),
    ("Beverages", "Food"),
    ("Billiards", "Sports"),
    ("Biography", "History"),
    ("Biology", "Biology"),
    ("Biotechnology", "Science"),
    ("Birding", "Recreation"),
    ("Board_Games", "Games"),
    ("Bondage", "Sexuality"),
    ("Boxing", "Combat_Sports"),
    ("BrE", "English"),
    ("Breeding", "Animal"),
    ("Brewing", "Food"),
    ("Broadcasting", "Media"),
    ("Building", "Construction"),
    ("Business", "Business"),
    ("Camping", "Outdoor_Recreation"),
    ("Canadian", "English"),
    ("Care", "Healthcare"),
    ("Career", "Work"),
    ("Cartography", "Geography"),
    ("Catering", "Food"),
    ("Catholicism", "Religion"),
    ("Celebrities", "People"),
    ("Celebrations", "Culture"),
    ("Cell_Biology", "Biology"),
    ("Censorship", "Law"),
    ("Ceremony", "Culture"),
    ("Charity", "Non-profit"),
    ("Chemistry", "Science"),
    ("Chess", "Games"),
    ("Child", "Family"),
    ("Children", "Family"),
    ("Childrens", "Family"),
    ("Childrens_Entertainment", "Entertainment"),
    ("Chinese", "Language"),
    ("Chiropractic", "Medicine"),
    ("Chores", "Housekeeping"),
    ("Christianity", "Religion"),
    ("Cleaning", "Housekeeping"),
    ("Climate_Change", "Environmental_Science"),
    ("Climate_Science", "Environmental_Science"),
    ("Clothing", "Fashion"),
    ("Cockfighting", "Sports"),
    ("Collaboration", "Communication"),
    ("Comedy", "Entertainment"),
    ("Commentary", "Communication"),
    ("Commerce", "Business"),
    ("Communication", "Communication"),
    ("Community", "Society"),
    ("Competition", "Sports"),
    ("Computer", "Computer_Science"),
    ("Computer_Science", "Computer_Science"),
    ("Conflict", "Warfare"),
    ("Conflict_Resolution", "Problem-Solving"),
    ("Conservation", "Environmental_Science"),
    ("Construction", "Construction"),
    ("Consumer_Rights", "Law"),
    ("Consumerism", "Business"),
    ("Cooking", "Food"),
    ("Cosmetics", "Fashion"),
    ("Costume", "Fashion"),
    ("Crafts", "Art"),
    ("Creativity", "Art"),
    ("Cricket", "Sports"),
    ("Crime", "Law"),
    ("Criminal", "Law"),
    ("Criminal_Justice", "Law"),
    ("Criminology", "Law"),
    ("Crossfit", "Sports"),
    ("Culinary", "Food"),
    ("Culture", "Culture"),
    ("Customer", "Business"),
    ("Customer_Service", "Business"),
    ("Cycling", "Sports"),
    ("Dance", "Performing_Arts"),
    ("Data_Analysis", "Statistics"),
    ("Data_Science", "Computer_Science"),
    ("Dating", "Relationship"),
    ("Death", "Life"),
    ("Debate", "Communication"),
    ("Decision_Making", "Problem-Solving"),
    ("Decor", "Interior_Design"),
    ("Dentistry", "Medicine"),
    ("Description", "Writing"),
    ("Design", "Art"),
    ("Development", "Improvement"),
    ("Disagreement", "Communication"),
    ("Disaster_Relief", "Humanitarian_Aid"),
    ("Discussion", "Communication"),
    ("Diseases", "Medicine"),
    ("Disorders", "Medicine"),
    ("Diving", "Water_Sports"),
    ("DIY", "Home_Improvement"),
    ("Doctrines", "Religion"),
    ("Dog", "Animal"),
    ("Drawing", "Art"),
    ("Drinking", "Food"),
    ("Drinks", "Food"),
]
merged2 = [
    ("Hotel", "Accommodation"),
    ("Insurance", "Insurance"),
    ("Interactions", "Communication"),
    ("Mythology", "Mythology"),
    ("Proverbs", "Proverbs"),
    ("Housekeeping", "Home_Improvement"),
    ("Mental_Health", "Mental_Health"),
    ("Art", "Art"),
    ("Performing", "Performing_Arts"),
    ("Phonetics", "Linguistics"),
    ("Gardening", "Outdoor_Recreation"),
    ("Performing_Arts", "Performing_Arts"),
    ("Genealogy", "History"),
    ("Negotiations", "Business"),
    ("Animal", "Zoology"),
    ("Toys", "Games"),
    ("Medical", "Medicine"),
    ("Organizational_Structure", "Management"),
    ("Hairdressing", "Fashion"),
    ("Interior_Design", "Interior_Design"),
    ("Home", "Household"),
    ("Probability", "Math"),
    ("Swimming", "Sports"),
    ("Wine", "Food"),
    ("Healthcare", "Medicine"),
    ("Tennis", "Sports"),
    ("Weather", "Science"),
    ("Power", "Energy"),
    ("Natural_Disasters", "Environment"),
    ("General", "Other"),
    ("Language", "Linguistics"),
    ("Social_Order", "Society"),
    ("Welfare", "Social_Issues"),
    ("History", "History"),
    ("Spirituality", "Religion"),
    ("Naval_History", "History"),
    ("Linguistics", "Linguistics"),
    ("Groups", "Society"),
    ("Journalism", "Media"),
    ("Radio", "Media"),
    ("Public_Speaking", "Communication"),
    ("Telephone", "Telecommunications"),
    ("Training", "Education"),
    ("Folklore", "Mythology"),
    ("Combat_Sports", "Sports"),
    ("English", "Language"),
    ("Landscape", "Geography"),
    ("Entomology", "Zoology"),
    ("Gossip", "Communication"),
    ("Psychology", "Mental_Health"),
    ("Furniture", "Household"),
    ("Sexual", "Sexuality"),
    ("Yoga", "Fitness"),
    ("Games", "Games"),
    ("Marine", "Maritime"),
    ("Traffic", "Transportation"),
    ("Formal_English", "Language"),
    ("Video", "Media"),
    ("Fantasy", "Fiction"),
    ("Learning", "Education"),
    ("Organizations", "Organization"),
    ("Sewing", "Crafting"),
    ("Survival", "Other"),
    ("Honesty", "Ethics"),
    ("Family", "Family"),
    ("Activity", "Sports"),
    ("Zoology", "Zoology"),
    ("Telecommunications", "Telecommunications"),
    ("Prison", "Law"),
    ("Stationery", "Office_Supplies"),
    ("Recognition", "Psychology"),
    ("Leadership", "Management"),
    ("terms", "Other"),
    ("Humanitarian", "Social_Work"),
    ("Politics", "Political_Science"),
    ("Taste", "Food"),
    ("Office", "Business"),
    ("Improvement", "Self_Improvement"),
    ("Wellbeing", "Mental_Health"),
    ("Physical_Description", "Anatomy"),
    ("Construction", "Engineering"),
    ("Planning", "Management"),
    ("Engineering", "Engineering"),
    ("Trade", "Business"),
    ("Quality_Control", "Manufacturing"),
    ("Holidays", "Culture"),
    ("Typography", "Writing"),
    ("Forestry", "Environment"),
    ("Retrieval", "Information_Science"),
    ("Information", "Information_Science"),
    ("Policy", "Political_Science"),
    ("Nature", "Science"),
    ("Supply_Chain", "Business"),
    ("Electrical", "Engineering"),
    ("Physiology", "Biology"),
    ("Hunting", "Sports"),
    ("Informal_Language", "Language"),
    ("Humor", "Entertainment"),
    ("Programming", "Computer_Science"),
    ("Problem_Solving", "Problem_Solving"),
    ("Professional_Development", "Education"),
    ("Human_Rights", "Law"),
    ("Maps", "Geography"),
    ("Religion", "Religion"),
    ("Etiquette", "Culture"),
    ("Pharmacy", "Medicine"),
    ("Media", "Media"),
    ("Psychiatry", "Mental_Health"),
    ("Warfare", "Military"),
    ("Research", "Science"),
    ("Sex", "Sexuality"),
    ("Nutrition", "Food"),
    ("Gambling", "Entertainment"),
    ("Idioms", "Language"),
    ("Products", "Business"),
    ("Restaurants", "Food"),
    ("Space", "Science"),
    ("Events", "Event"),
    ("Transportation", "Transportation"),
    ("Emergency_Management", "Law"),
    ("Time", "Science"),
    ("Logic", "Math"),
    ("Sound", "Physics"),
    ("Finance", "Business"),
    ("Immigration", "Law"),
    ("Textile", "Manufacturing"),
    ("Funeral", "Culture"),
    ("Tourism", "Travel"),
    ("Interaction", "Communication"),
    ("Football", "Sports"),
    ("Sports", "Sports"),
    ("Safety", "Law"),
    ("Western_Culture", "Culture"),
    ("Networking", "Business"),
    ("Entrepreneurship", "Business"),
    ("Kitchen", "Household"),
    ("Social_Justice", "Social_Issues"),
    ("Mining", "Engineering"),
    ("Governmental_structures", "Government"),
    ("News", "Media"),
    ("Formal", "Language"),
    ("Rural", "Geography"),
    ("Humanitarian_Aid", "Social_Work"),
    ("Formal_Communication", "Writing"),
    ("Sexual_Health", "Medicine"),
]
merged3 = [
    ("Figurative", "Language"),
    ("Workplace", "Work"),
    ("Cuisine", "Food"),
    ("Household", "Household"),
    ("Oil", "Energy"),
    ("Performance", "Arts"),
    ("Navy", "Military"),
    ("Sociology", "Social_Science"),
    ("Intellectual_Property", "Law"),
    ("Shopping", "Business"),
    ("Spanish", "Language"),
    ("Issues", "Social_Issues"),
    ("Project", "Project_Management"),
    ("Geology", "Science"),
    ("Sport", "Sports"),
    ("Emotion", "Psychology"),
    ("Education", "Education"),
    ("Relations", "Relationships"),
    ("Public", "Public_Service"),
    ("Landscaping", "Outdoor_Recreation"),
    ("Music", "Arts"),
    ("Philosophy", "Humanities"),
    ("War", "Military"),
    ("Problem-solving", "Problem_Solving"),
    ("Information_Technology", "Technology"),
    ("Relationships", "Relationships"),
    ("Writing", "Writing"),
    ("Resources", "Information_Science"),
    ("Outdoor_Recreation", "Outdoor_Recreation"),
    ("Home_Improvement", "Home_Improvement"),
    ("Social", "Social_Science"),
    ("Film", "Entertainment"),
    ("Motivation", "Self_Improvement"),
    ("Naval", "Military"),
    ("Marriage", "Relationships"),
    ("Video_Games", "Entertainment"),
    ("Science", "Science"),
    ("Metaphor", "Language"),
    ("Emotional", "Psychology"),
    ("Equestrianism", "Animals"),
    ("Fashion", "Fashion"),
    ("Statistics", "Math"),
    ("NAmE", "Other"),
    ("Style", "Fashion"),
    ("Fundraising", "Non_Profit"),
    ("Economics", "Economics"),
    ("Accommodation", "Hospitality"),
    ("Computer_Science", "Technology"),
    ("Everyday", "Everyday_Life"),
    ("Children's_Entertainment", "Entertainment"),
    ("leech", "Animal"),
    ("Electrical_Engineering", "Engineering"),
    ("Formal_Writing", "Writing"),
    ("Plumbing", "Home_Improvement"),
    ("Leatherworking", "Crafting"),
    ("Horticulture", "Agriculture"),
    ("Ethics", "Philosophy"),
    ("Ethnicity", "Culture"),
    ("Internet", "Technology"),
    ("Governmental", "Government"),
    ("Manufacturing", "Manufacturing"),
    ("Media", "Media"),
    ("Supplies", "Office_Supplies"),
    ("Crafting", "Crafting"),
    ("Culture", "Culture"),
    ("Teamwork", "Management"),
    ("Information_Science", "Information_Science"),
    ("Espionage", "Military"),
    ("Visual", "Arts"),
    ("Naval_terms", "Military"),
    ("Transport", "Transportation"),
    ("Paper", "Office_Supplies"),
    ("Perseverance", "Personal_Development"),
    ("Production", "Manufacturing"),
    ("Social_Work", "Social_Work"),
    ("Management", "Management"),
    ("Life", "Other"),
    ("Accessibility", "Social_Issues"),
    ("Ecology", "Environmental_Science"),
    ("Legal", "Law"),
    ("commentary", "Writing"),
    ("Administrative", "Administration"),
    ("Mail", "Communication"),
    ("Business", "Business"),
    ("Lifestyle", "Everyday_Life"),
    ("Society", "Social_Science"),
    ("Supernatural", "Mythology"),
    ("Measurement", "Math"),
    ("Sailing", "Water_Sports"),
    ("Everyday_life", "Everyday_Life"),
    ("Occult", "Mythology"),
    ("Sensory", "Science"),
    ("International", "International_Relations"),
    ("Uniforms", "Fashion"),
    ("Event", "Event"),
    ("Work", "Work"),
    ("Personal_Development", "Personal_Development"),
    ("Studies", "Education"),
    ("Firearms", "Weapons"),
    ("Genetics", "Biology"),
    ("Health", "Health"),
    ("Information_Retrieval", "Information_Science"),
    ("Leisure", "Recreation"),
    ("Social_Issues", "Social_Issues"),
    ("Speech", "Communication"),
    ("Exploration", "Science"),
    ("LGBT", "LGBTQ+"),
    ("Veterinary", "Animals"),
    ("Emergency", "Emergency_Services"),
    ("Exercise", "Fitness"),
    ("Employment", "Work"),
    ("Reputation", "Social_Issues"),
    ("Violence", "Violence"),
    ("Craft", "Crafting"),
    ("Intelligence", "Law"),
    ("Marketing", "Business"),
    ("Investigation", "Law"),
    ("Translation", "Language"),
    ("Non-profit", "Non_Profit"),
    ("Timekeeping", "Office_Supplies"),
    ("Drug_Abuse", "Health"),
    ("Service", "Service_Industry"),
    ("Marine_Biology", "Biology"),
    ("Royalty", "History"),
    ("Human", "Humanities"),
    ("Children's", "Entertainment"),
    ("Self-Help", "Self_Improvement"),
    ("Formal_Language", "Language"),
    ("Social_Media", "Media"),
    ("Environmental", "Environmental_Science"),
    ("Maritime", "Transportation"),
    ("Pets", "Animals"),
    ("Mechanics", "Engineering"),
    ("Services", "Service_Industry"),
    ("Nautical", "Transportation"),
    ("Erotica", "Entertainment"),
    ("Meteorology", "Science"),
    ("Legal_terms", "Law"),
    ("Parenting", "Family"),
    ("Urban_Planning", "Government"),
]
merged4 = [
    ("Travel", "Travel"),
    ("Geography", "Geography"),
    ("Inheritance", "Law"),
    ("Education", "Education"),
    ("Photography", "Arts"),
    ("Language", "Language"),
    ("Psychology", "Social_Science"),
    ("Animal", "Animals"),
    ("Medicine", "Medicine"),
    ("Speaking", "Communication"),
    ("People", "Society"),
    ("Taxidermy", "Science"),
    ("Mythology", "Mythology"),
    ("Industrial", "Industry"),
    ("Housing", "Housing"),
    ("Security", "Security"),
    ("Human_Resources", "Business"),
    ("Justice", "Law"),
    ("Literature", "Humanities"),
    ("Horse_Racing", "Sports"),
    ("Mental", "Mental_Health"),
    ("Media", "Media"),
    ("Business", "Business"),
    ("Strategy", "Business"),
    ("Military", "Military"),
    ("Cybersecurity", "Security"),
    ("Farming", "Agriculture"),
    ("Repair", "Service_Industry"),
    ("Urban", "Urban_Planning"),
    ("Theology", "Religion"),
    ("Drug", "Health"),
    ("Materials", "Material_Science"),
    ("Negotiation", "Business"),
    ("Crafting", "Crafting"),
    ("Home_Improvement", "Home_Improvement"),
    ("Social_Science", "Social_Science"),
    ("Risk_Management", "Business"),
    ("Time_Management", "Self_Improvement"),
    ("Law_Enforcement", "Law"),
    ("Personality", "Psychology"),
    ("Gas", "Energy"),
    ("Communication", "Communication"),
    ("Emergency_Services", "Emergency_Services"),
    ("Project_Management", "Management"),
    ("Gender", "Social_Science"),
    ("Poetry", "Literature"),
    ("Luxury", "Fashion"),
    ("Fashion", "Fashion"),
    ("Industry", "Industry"),
    ("Illegal_terms", "Law"),
    ("Informal", "Language"),
    ("History", "History"),
    ("Retail", "Business"),
    ("Regulation", "Law"),
    ("Mystery", "Literature"),
    ("Equestrian", "Animals"),
    ("Horror", "Fiction"),
    ("Problem", "Problem_Solving"),
    ("Success", "Self_Improvement"),
    ("Slang", "Language"),
    ("Interior", "Interior_Design"),
    ("Packaging", "Manufacturing"),
    ("Superstition", "Mythology"),
    ("Social_Issues", "Social_Issues"),
    ("Material_Science", "Material_Science"),
    ("Political_Science", "Political_Science"),
    ("Fishing", "Sports"),
    ("Informal_Communication", "Communication"),
    ("International_Relations", "International_Relations"),
    ("Romance", "Relationships"),
    ("Husbandry", "Agriculture"),
    ("Writing", "Writing"),
    ("Jewelry", "Fashion"),
    ("Theatre", "Arts"),
    ("Hygiene", "Health"),
    ("Problem-Solving", "Problem_Solving"),
    ("Riding", "Equestrian"),
    ("Privacy", "Law"),
    ("Horse", "Animals"),
    ("Work", "Work"),
    ("Nuclear", "Energy"),
    ("Relationship", "Relationships"),
    ("Public_Health", "Health"),
    ("Love", "Relationships"),
    ("Surveillance", "Security"),
    ("Printing", "Manufacturing"),
    ("Manufacturing", "Manufacturing"),
    ("Electronics", "Technology"),
    ("Museums", "History"),
    ("Science", "Science"),
    ("Solving", "Problem_Solving"),
    ("Hobbies", "Recreation"),
    ("Information_Science", "Information_Science"),
    ("Water_Sports", "Sports"),
    ("Naval_Engineering", "Engineering"),
    ("Innovation", "Business"),
    ("Agriculture", "Agriculture"),
    ("Meetings", "Business"),
    ("Physics", "Science"),
    ("Pharmaceuticals", "Medicine"),
    ("Drink", "Food"),
    ("Military_terms", "Military"),
    ("Recreation", "Recreation"),
    ("Mathematics", "Math"),
    ("Philanthropy", "Social_Work"),
    ("Public_Policy", "Law"),
    ("Political_terms", "Political_Science"),
    ("Labor", "Work"),
    ("Hardware", "Technology"),
    ("Proverb", "Literature"),
    ("Government", "Government"),
    ("Animals", "Animals"),
    ("Self-improvement", "Self_Improvement"),
    ("Golf", "Sports"),
    ("Public_Service", "Government"),
    ("Wildlife", "Animals"),
    ("Energy", "Energy"),
    ("Speculative", "Fiction"),
    ("structures", "Architecture"),
    ("Service_Industry", "Service_Industry"),
    ("Activities", "Recreation"),
    ("Editing", "Writing"),
    ("Visual_Arts", "Arts"),
    ("Self_Improvement", "Self_Improvement"),
    ("chores", "Work"),
    ("Elections", "Government"),
    ("Neuroscience", "Science"),
    ("Drugs", "Health"),
    ("Festivals", "Culture"),
    ("Storytelling", "Writing"),
    ("Earth", "Science"),
    ("Organization", "Management"),
    ("Food", "Food"),
    ("Physical", "Anatomy"),
    ("Academia", "Education"),
    ("Philosophy", "Philosophy"),
    ("Tradition", "Culture"),
    ("Relationships", "Relationships"),
    ("Perfume", "Fashion"),
    ("Environmental_Science", "Environmental_Science"),
    ("Humanities", "Humanities"),
    ("Morality", "Philosophy"),
]
merged5 = [
    ("Biology", "Biology"),
    ("Hospitality", "Hospitality"),
    ("Fiction", "Fiction"),
    ("Recreation", "Recreation"),
    ("Real_Estate", "Real_Estate"),
    ("Anatomy", "Anatomy"),
    ("Paranormal", "Mythology"),
    ("Language", "Language"),
    ("Geometry", "Math"),
    ("Rhetoric", "Writing"),
    ("Real", "Real_Estate"),
    ("Education", "Education"),
    ("Social_Science", "Social_Science"),
    ("Administration", "Government"),
    ("Equestrian", "Animals"),
    ("Security", "Security"),
    ("Optics", "Physics"),
    ("Sciences", "Science"),
    ("Accidents", "Law"),
    ("Law", "Law"),
    ("Family", "Family"),
    ("Navigation", "Transportation"),
    ("Monarchy", "Government"),
    ("Religion", "Religion"),
    ("Communication", "Communication"),
    ("Informal_Speech", "Language"),
    ("Military", "Military"),
    ("Logistics", "Business"),
    ("Architecture", "Architecture"),
    ("Movements", "Sports"),
    ("Fitness", "Fitness"),
    ("Management", "Management"),
    ("Wisdom", "Philosophy"),
    ("Painting", "Arts"),
    ("Sexuality", "Sexuality"),
    ("Math", "Math"),
    ("Psychology", "Psychology"),
    ("Political", "Political_Science"),
    ("Society", "Social_Science"),
    ("Technology", "Technology"),
    ("Literature", "Literature"),
    ("Material", "Material_Science"),
    ("Sports", "Sports"),
    ("Memory", "Psychology"),
    ("Oceanography", "Science"),
    ("Grammar", "Language"),
    ("Tools", "Tools"),
    ("Office_Supplies", "Office_Supplies"),
    ("Business", "Business"),
    ("Philosophy", "Philosophy"),
    ("Drug_Culture", "Social_Issues"),
    ("Mental_Health", "Mental_Health"),
    ("Science", "Science"),
    ("Writing", "Writing"),
    ("Personal", "Other"),
    ("Sculpture", "Arts"),
    ("Arts", "Arts"),
    ("Problem-Solving", "Problem_Solving"),
    ("Fashion", "Fashion"),
    ("History", "History"),
    ("Urban_Planning", "Urban_Planning"),
    ("Fire", "Emergency_Services"),
    ("Animals", "Animals"),
    ("Environment", "Environmental_Science"),
    ("Publishing", "Media"),
    ("Other", "Other"),
    ("Taboo", "Social_Issues"),
    ("Enforcement", "Law"),
    ("Health", "Health"),
    ("Software", "Technology"),
    ("Social_Work", "Social_Work"),
    ("LGBTQ+", "LGBTQ+"),
    ("Botany", "Biology"),
    ("Medicine", "Medicine"),
    ("Scheduling", "Self_Improvement"),
    ("Estate", "Real_Estate"),
    ("Everyday_Life", "Everyday_Life"),
    ("Mythology", "Mythology"),
    ("Entertainment", "Entertainment"),
    ("Government", "Government"),
    ("Sales", "Business"),
    ("Violent", "Violence"),
    ("Weapons", "Weapons"),
    ("Libraries", "Libraries"),
    ("Library", "Libraries"),
    ("Engineering", "Engineering"),
    ("Risk", "Risk_Management"),
    ("Television", "Entertainment"),
    ("Woodworking", "Crafting"),
    ("Interior_Design", "Interior_Design"),
    ("Culture", "Culture"),
    ("Political_Science", "Political_Science"),
    ("Non-Profit", "Non_Profit"),
    ("Work", "Work"),
    ("Transportation", "Transportation"),
]
custom = [
    ("Academia", "Education"),
    ("Activity", "Other"),
    ("Agriculture", "Agriculture"),
    ("Animal", "Biology"),
    ("Art", "Art"),
    ("Biology", "Biology"),
    ("Business", "Business"),
    ("Communication", "Communication"),
    ("Computer_Science", "Technology"),
    ("Construction", "Industry"),
    ("Crafting", "Art"),
    ("Culture", "Social_Science"),
    ("Economics", "Economics"),
    ("Education", "Education"),
    ("Emergency_Services", "Other"),
    ("Energy", "Science"),
    ("Engineering", "Technology"),
    ("Entertainment", "Entertainment"),
    ("Environmental_Science", "Environmental_Science"),
    ("Event", "Event"),
    ("Everyday_life", "Other"),
    ("Family", "Social_Science"),
    ("Fashion", "Fashion"),
    ("Fiction", "Writing"),
    ("Fitness", "Health"),
    ("Food", "Food"),
    ("Games", "Games"),
    ("Geography", "Geography"),
    ("Government", "Government"),
    ("Health", "Health"),
    ("History", "History"),
    ("Home_Improvement", "Other"),
    ("Hospitality", "Travel"),
    ("Household", "Household"),
    ("Housing", "Real_Estate"),
    ("Humanities", "Humanities"),
    ("Industry", "Industry"),
    ("Information_Science", "Technology"),
    ("Insurance", "Business"),
    ("Interior_Design", "Art"),
    ("International_Relations", "Social_Science"),
    ("Law", "Law"),
    ("Libraries", "Education"),
    ("Linguistics", "Linguistics"),
    ("Management", "Management"),
    ("Manufacturing", "Industry"),
    ("Material_Science", "Science"),
    ("Math", "Science"),
    ("Media", "Media"),
    ("Medicine", "Medicine"),
    ("Mental_Health", "Mental_Health"),
    ("Military", "Military"),
    ("Mythology", "Religion"),
    ("Non_Profit", "Other"),
    ("Office_Supplies", "Other"),
    ("Outdoor_Recreation", "Recreation"),
    ("Performing_Arts", "Art"),
    ("Personal_Development", "Self_Improvement"),
    ("Political_Science", "Political_Science"),
    ("Problem_Solving", "Problem_Solving"),
    ("Proverbs", "Writing"),
    ("Real_Estate", "Real_Estate"),
    ("Recreation", "Recreation"),
    ("Relationships", "Social_Science"),
    ("Religion", "Religion"),
    ("Science", "Science"),
    ("Security", "Security"),
    ("Self_Improvement", "Self_Improvement"),
    ("Service_Industry", "Business"),
    ("Sexuality", "Social_Science"),
    ("Social_Issues", "Social_Science"),
    ("Social_Science", "Social_Science"),
    ("Social_Work", "Social_Science"),
    ("Sports", "Sports"),
    ("Technology", "Technology"),
    ("Telecommunications", "Technology"),
    ("Tools", "Military"),
    ("Transportation", "Transportation"),
    ("Travel", "Travel"),
    ("Violence", "Military"),
    ("Weapons", "Military"),
    ("Work", "Business"),
    ("Writing", "Writing"),
    ("Zoology", "Zoology"),
]


def validate_custom():
    all_mapping = [*merged1, *merged2, *merged3, *merged4, *merged5, *custom]
    for _, cat in custom:
        for start, end in all_mapping:
            if cat == start and start != end:
                print(f"({start}, {end})")


def find_new_category(cat, mapping):
    for old, new_category in mapping:
        if old == cat:
            if old == new_category:
                return True, cat
            return False, new_category
    return True, cat


def run():
    # logging.basicConfig(
    #     filename="merge_categories.log",
    #     level=logging.DEBUG,
    #     format="%(levelname)s:%(name)s: %(asctime)s %(message)s",
    # )
    # logger.info("Start merge")

    anki_invoke("clearUnusedTags")
    tags = anki_invoke("getTags")
    # result = {}
    # for tag in tags:
    #     cids = anki_invoke("findCards", query=f"deck:KEXP::Read tag:{tag}")
    #     result[tag] = len(cids)

    ltags = set(filter(lambda tag: tag.startswith("L_"), tags))
    tags = set(
        filter(lambda tag: not tag.startswith("K_") and not tag.startswith("L_"), tags)
    )
    print(len(tags), len(ltags))
    return
    all_mapping = [*custom, *merged1, *merged2, *merged3, *merged4, *merged5]

    for tag in tqdm(tags):
        reached = False
        prevent_loop_limit = 15
        path = [tag]
        current = tag
        while not reached and prevent_loop_limit > 0:
            reached, new_category = find_new_category(current, all_mapping)
            current = new_category
            path.append(new_category)
            prevent_loop_limit -= 1

        logger.info("->".join(path))
        if prevent_loop_limit <= 0:
            logger.error("loop occurred")
            break

        if tag == current:
            continue

        nids = anki_invoke("findNotes", query=f"deck:KEXP::Read tag:{tag}")
        if not len(nids):
            continue
        anki_invoke(
            "replaceTags", notes=nids, tag_to_replace=tag, replace_with_tag=current
        )

    # for old, new_category in merged:
    #     tags.add(new_category)
    #     if old in tags:
    #         tags.remove(old)
    #
    # logger.info(f"size after merge {len(tags)}")
    #
    #
    # with open("categories.json", mode="w", encoding="utf-8") as f:
    #     f.write(json.dumps(list(tags)))


def find_small_categories():
    tags = anki_invoke("getTags")
    result = []
    for tag in tags:
        cids = anki_invoke("findCards", query=f"deck:KEXP::Read tag:{tag}")
        if len(cids) < 10:
            result.append(tag)
    print(result)


def get_ai_tags():
    tags = anki_invoke("getTags")
    return list(
        filter(lambda tag: not tag.startswith("K_") and not tag.startswith("L_"), tags)
    )


def output_categories():
    tags = get_ai_tags()

    with open("categories.json", mode="w", encoding="utf-8") as f:
        f.write(json.dumps(tags))


if __name__ == "__main__":
    run()
    # validate_custom()
    # find_small_categories()
